USERNAME = 150
EMAIL = 254
ROLE = 30
FIRST_NAME = 30
LAST_NAME = 30

CONFIRMATION_CODE_LENGTH = 4
USER = 'user'
ADMIN = 'admin'
MODERATOR = 'moderator'

ROLE_CHOICES = [
    (USER, USER),
    (ADMIN, ADMIN),
    (MODERATOR, MODERATOR),
]
